package Section3;

public class ExceptionArrayIndex {

	public static void main(String[] args) {
		int a[]= {4,5,6,7,9};
		System.out.println("start journy");
		System.out.println(a[6]);
		System.out.println("end point");

	}

}
              //start journy
               //Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 6
                 //at Section3.ExceptionArrayIndex.main(ExceptionArrayIndex.java:8)

